FROM golang:1.22 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o bootstrap ./cmd/lambda/main.go

FROM public.ecr.aws/lambda/go:1
COPY --from=builder /app/bootstrap ${LAMBDA_TASK_ROOT}
